site_name: "2024 Newspeak House Fellowship Candidates"
site_url: "https://2024.newspeak.house"
theme:
  name: simple-blog
  custom_dir: custom_theme
  favicon: images/favicon.png
  extra_files: CNAME
nav:
  - Home: index.md
  - Visit Us: visit_us.md
  - Stay at Newspeak House: night_guests_form.md
  - Wellbeing: wellbeing.md
  - Experiments: experiments.md
  - Sensing: sensing.md
  - Books: books.md
  - Dreamjob™: dreamjob.md
extra_css: 
  - stylesheets/style.css
extra:
  analytics:
    provider: custom

